### PR TITLE
#872 added appveyor config

### PR DESCRIPTION
**Pull request by exper0**
#872 added appveyor config

### CODE REVIEW

**Comment by karato** [comment]
@exper0 Let me find a reviewer for this pull request, thanks for submitting it

**Comment by karato** [comment]
@krzyk review it

**Comment by krzyk** [comment]
@exper0 please add a link to the original issue and description of work done in the PR description

**Comment by exper0** [comment]
@krzyk added description in PR, it's about #872 - setting up appveyor build

**Comment by krzyk** [comment]
@exper0 appveyor build fails, is that expected?

**Comment by exper0** [comment]
@krzyk probably yes - build fails because command
`mvn clean install -B -Dmaven.test.skip=true` fails. This is exactly how it behaves on my local workstation but I'm not sure why it is

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by exper0** [comment]
@krzyk build is successful now

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by karato** [comment]
@rultor deploy now pls

**Comment by ypshenychka** [comment]
@krzyk 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by krzyk** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@krzyk thanks

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by karato** [comment]
@krzyk paied 10 mins to @ypshenychka for QA review (payment ID is `74134687`)... Much obliged! I have added **19 mins** to your account in payment "74134698", 16 hours and 43 mins spent... review comments (c=4) added as a bonus... +19 to your rating, your total score is [+3037](http://www.netbout.com/b/35035?open=rating)

**Pull request merged**
