### PR TITLE
#863 Fixed Reference-style markdown images do not work in bouts 

### PR DESCRIPTION
**Pull request by kujtimiihoxha**
For : #863
 - Fixed pattern to recognize reference style

### CODE REVIEW

**Comment by karato** [comment]
@kujtimiihoxha I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by karato** [comment]
@dmzaytsev review it please, it is a rather short pull request, no need to do a full code review

**Comment by dmzaytsev** [comment]
@kujtimiihoxha what about a test?

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Test added

**Comment by kujtimiihoxha** [comment]
@kujtimiihoxha something is wrong with netbout-client, it does not have to do with my pull request.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha try close/open the PR to trigger a new build

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  it is not triggering rebuild at AppVeyor

**Comment by dmzaytsev** [comment]
@kujtimiihoxha let's try to merge

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Thanks for your contribution, **19 mins** was added to your account, payment ID is `77134134`, 7 hours and 5 mins spent total

review comments (c=4) added as a bonus

+19 to your rating, your total score is [+3097](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy now pls

**Pull request merged**
