### PR TITLE
Added to download jquery-textcomplete during build generation (Issue #723)

### PR DESCRIPTION
**Pull request by antonini**
For Issue #723.

* Added npm and bower to netbout-web project;
* Added to download jquery-textcomplete while generating build;
* Created script to be execute on postinstall hook of bower;
* Thridparty js folder created dynamically with thirdparty javascripts (Also it is supporting JavaScript Source Maps);

### CODE REVIEW

**Comment by karato** [comment]
@antonini Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@pinaf review it

**Comment by pinaf** [comment]
@dmzaytsev A quick question: is it alright to add these dependencies to the project?

**Comment by dmzaytsev** [comment]
@pinaf yep, see https://github.com/yegor256/netbout/pull/712#issuecomment-114275100

**Comment by pinaf** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by karato** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by karato** [comment]
@rultor deploy

**Comment by elenavolokhova** [comment]
@pinaf 
According to our [quality rules](http://www.teamed.io/qa.html):
 > The code reviewer found at least three problems in the code.
 
 There were no issues found during review.
Please confirm that you will try to find at least three problems next time.

**Comment by pinaf** [comment]
@elenavolokhova I confirm

**Comment by elenavolokhova** [comment]
@karato  Quality is acceptable here.

**Comment by karato** [comment]
> @karato  Quality is acceptable here.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by karato** [comment]
@pinaf just added 10 mins to @elenavolokhova (for QA), payment ID is `64304731`. Many thanks! **18 mins** were added to your account in Transaction ID `AP-20F30222FN017990T` (task took 9 hours and 25 mins). you're getting extra minutes here (c=3). added +18 to your rating, now it is equal to [+4848](http://www.netbout.com/b/35128?open=rating)

**Pull request merged**
