### PR TITLE
#1038 upgraded to latest takes, fixed tests

### PR DESCRIPTION
**Pull request by dmzaytsev**
For #1038 
* upgraded to latest takes
* fixed tests according to https://github.com/yegor256/takes/issues/642

### CODE REVIEW

**Comment by karato** [comment]
@dmzaytsev Let me find a reviewer for this pull request, thanks for submitting it

**Comment by karato** [comment]
@dmzaytsev no need to do code review here, it's a small pull request from the architect

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@krzyk do this review

**Pull request merged**
