### PR TITLE
#862 prevented bout renaming to empty string

### PR DESCRIPTION
**Pull request by CarlosGines**
Fixes for #862:
- Modified bout.js to prevent renaming with an empty string.

### CODE REVIEW

**Comment by karato** [comment]
@carlosgines Thanks for the pull request, let me find a reviewer..

**Comment by karato** [comment]
@dmzaytsev review this pls (it's a rather short pull request)

**Comment by dmzaytsev** [comment]
@CarlosGines what about a test?

**Comment by dmzaytsev** [comment]
@CarlosGines also I think the fix should prevent bout names that contain only spaces

**Comment by CarlosGines** [comment]
@dmzaytsev Alright! For the test I create a casperjs test in a new file, right?

**Comment by dmzaytsev** [comment]
@CarlosGines sure

**Comment by CarlosGines** [comment]
New fixes for #862:
- Modified bout.js to prevent renaming with an only space string.
- Added casperjs test.

**Comment by CarlosGines** [comment]
@dmzaytsev review again please!

**Comment by dmzaytsev** [comment]
@CarlosGines thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by CarlosGines** [comment]
@karato I have 2 questions.
- How should I proceed at his point when PR is closed? Should I notify you? Should I ask the issue reporter to close the ticket?
- When is it considered that the task is finished (for counting bonuses or meeting deadlines)? Once the PR is closed? Once the issued is closed?

**Comment by karato** [comment]
@dmzaytsev Thanks for your contribution, **20 mins** was added to your account, payment ID is `78662076`, 39 hours and 55 mins spent total

you're getting extra minutes here (c=5)

added +20 to your rating, now it is equal to [+3589](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
