### PR TITLE
 #1055 upgraded cobertura plugin

### PR DESCRIPTION
**Pull request by dmzaytsev**
for #1055 
* upgraded cobertura plugin
* enabled site-deployment

### CODE REVIEW

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Many thanks, I will find someone to review it before we merge

**Comment by karato** [comment]
@dmzaytsev no code review is required here since it's too short and from the architect

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@krzyk review it

**Comment by krzyk** [comment]
@yegor256 there is a problem with the small PRs, I was assigned even for this short PR, which is marked invalid

**Comment by yegor256** [comment]
@krzyk yeah, I see... ignore it

**Pull request merged**
