### PR TITLE
#576 Provide project estimate

### PR DESCRIPTION
**Pull request by komaz**
Proposed fix for issue #576. That's a completely a wild guess, not sure whether it is useful.

### CODE REVIEW

**Comment by karato** [comment]
@komaz Thanks, I will find someone to review this PR soon

**Comment by karato** [comment]
@caarlos0 do this review

**Comment by caarlos0** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor merge please

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by karato** [comment]
@rultor deploy

**Comment by ypshenychka** [comment]
@caarlos0  
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. Try to find at least three problems while future reviews.

Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by caarlos0** [comment]
@ypshenychka sure, I'll try

**Comment by ypshenychka** [comment]
@caarlos0 Thank you.

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks a lot, next time everybody should try to make it better

**Comment by karato** [comment]
@caarlos0 I added 10 mins to @ypshenychka (for QA review) in transaction 58270053... Many thanks! **17 mins** were added to your account in Transaction ID `AP-54G48320ER449983E` (task took 4 hours and 25 mins)... review comments (c=2) added as a bonus... +17 to your rating, your total score is [+2075](http://www.netbout.com/b/35095?open=rating)

**Pull request merged**
