### PR TITLE
#918 post a new message using ctrl-enter

### PR DESCRIPTION
**Pull request by dmzaytsev**
For #918

* now it's possible to post a new message using CTRL+ENTER combination

### CODE REVIEW

**Comment by karato** [comment]
@dmzaytsev Many thanks for the PR, let me find a reviewer for it

**Comment by karato** [comment]
@dmzaytsev no need to do code review here, it's a small pull request from the architect

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by longtimeago** [comment]
@rultor deploy

**Pull request merged**
