### PR TITLE
#567 prevent duplicate messages in bouts

### LINKED ISSUE #567: prevent duplicate messages in bouts
When I click "post message" twice, I get two identical messages. It's a bug

### PR DESCRIPTION
**Pull request by mbarbieri**
Add a JQuery fn to avoid multiple submission of the same form and attached to the *Post message* form.
Fixes #567

### CODE REVIEW

**Comment by karato** [comment]
@mbarbieri Thanks, someone will review your pull request soon

**Comment by karato** [comment]
@dmzaytsev the pull request is rather small, pls review it

**Comment by dmzaytsev** [comment]
@mbarbieri did you test it on the local instance?

**Comment by mbarbieri** [comment]
@dmzaytsev yes, working fine.

**Comment by dmzaytsev** [comment]
@mbarbieri thanks!

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by karato** [comment]
@rultor please deploy

**Comment by elenavolokhova** [comment]
@karato As far as there was not usual CR+architect flow quality is acceptable here.

**Comment by karato** [comment]
> @karato As far as there was not usual CR+architect flow quality is acceptable here.

@elenavolokhova thanks for the QA review, we'll work better next time

**Comment by karato** [comment]
@dmzaytsev I added 10 mins to @elenavolokhova (for QA review) in transaction 59060679... Thank you, I have added **18 mins** to your account in payment/transaction "`59060691`", time consumed: 2 hours and 33 mins... you're getting extra minutes here (c=3)... +18 to your rating, your total score is [+2583](http://www.netbout.com/b/35166?open=rating)

**Pull request merged**
