### PR TITLE
#992 Deployment failed due to the coverage report not exists

### PR DESCRIPTION
**Pull request by kujtimiihoxha**
For #992
  - Added clean install to the last command because just removing clean did not work.

### CODE REVIEW

**Comment by karato** [comment]
@kujtimiihoxha Thanks for the pull request, let me find a reviewer..

**Comment by karato** [comment]
@dmzaytsev pull request is rather short, review it please

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Much appreciated! **16 mins** was added to your account, payment ID `78184387`, time spent is 30 hours and 22 mins. review comments (c=1) added as a bonus. +16 to your rating, your total score is [+3362](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
