### PR TITLE
#868 fixed temp file removal on windows machines

### PR DESCRIPTION
**Pull request by exper0**
#868 fixed temp file removal on windows machines

### CODE REVIEW

**Comment by karato** [comment]
@exper0 Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
@dmzaytsev review it please, it is a rather short pull request, no need to do a full code review

**Comment by dmzaytsev** [comment]
@exper0 you have a few checkstyle issues, see Travis's log for details
please fix it

btw you can do `mvn clean install -Pqulice` before push

**Comment by exper0** [comment]
@dmzaytsev I had some problems with qulice during initial build(even without my changes) - it just fails the build. May be I did something wrong, let me check it once again

**Comment by exper0** [comment]
@dmzaytsev done

**Comment by dmzaytsev** [comment]
@exper0 I see Travis build failed, it's temporary issue
could you close this PR and open it back to trigger a new Travis's build ?
or push something for the same purpuse

**Comment by exper0** [comment]
@dmzaytsev done, build checks passed

**Comment by dmzaytsev** [comment]
@exper0 thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev **19 mins** sent to your balance (ID `73037749`), many thanks! It took 16 hours and 50 mins.

review comments (c=4) added as a bonus

+19 to your rating, your total score is [+1253](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
