### PR TITLE
#588: Application Error during access to some pages

### PR DESCRIPTION
**Pull request by bdragan**
#588: Application Error during access to some pages.

### CODE REVIEW

**Comment by karato** [comment]
@bdragan Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
@pinaf do this review

**Comment by bdragan** [comment]
@pinaf Could you please do the review? In 48 hours the solution will be discarded by the product manager. :) Thanks!

**Comment by pinaf** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by karato** [comment]
@rultor please deploy

**Comment by ypshenychka** [comment]
@pinaf 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by pinaf** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@pinaf Thank you

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks a lot, next time everybody should try to make it better

**Comment by karato** [comment]
@pinaf I added 10 mins to @ypshenychka (for QA review) in transaction 69051213... done, I added **17 mins** in payment `AP-1H975850F1911523F`, 75 hours and 17 mins spent to complete this... review comments (c=2) added as a bonus... +17 to your rating, your total score is [+3962](http://www.netbout.com/b/35128?open=rating)

**Pull request merged**
