### PR TITLE
Jacoco instead of cobertura 

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #1118 . 
Switched to jacoco for code coverage.
Changes done: 

In the first commit (2476d5a) I simply replaced cobertura with jacoco and it worked the same as before (almost...) meaning that: 

The cobertura profile was being executed at ``mvn site`` and right after it the coveralls profile was also executed -> this worked after the change to jacoco, but with a **big flaw**: the coveralls profile  executed for each module and thus sending sepparate reports to coveralls.io, instead of an aggregate one (I tested with one of my repos, by putting its token in pom.xml)
coveralls

So in the second commit (188c759) I did the following change: 
jacoco profile stays and can be called with ``-Pjacoco`` - it is not bound to the site phase anymore... I never understood why it was bound to it to begin with. 
The coveralls plugin is not wrapped in a profile anymore and the report has to be called by ``coveralls:report`` .  I tried leaving it warpped in the profile, but for some reason ``mvn clean install -Pjacoco,coveralls`` did not work. However, ``mvn clean install -Pjacooc coveralls:report`` works just fine.

**[later edit]**
In the third commit, fixing a bug, jacoco is not a profile anymore, but a simple plugin which is always run.

This is the best approach, from my point of view: you can run the jacoco profile whenever you want to check the coverage (it might be enhanced in the future to add minimum benchmarks for coverage etc) and right after it, a call to ``coveralls:report`` to send it up to www.coveralls.io

Finally, as I added in ``.travis.yml``, a complete build with coverage and report looks like this:
``mvn clean install -Pqulice coverals:report``

I don't see the point of adding it to rultor builds (travis is enough, makes no sense to send the same report from more places), and also it would be a little more complicated, since you would most likely need to specify the coveralls repo token - which is not necessary with travis (remember, this token has to be kept **secret**, so not as easy to just specify it in pom.xml)

### CODE REVIEW

**Comment by amihaiemil** [comment]
@krzyk maybe you can have a quick look to see if it's ok with you (just to speed things up) :D

**Comment by karato** [comment]
@amihaiemil Thanks, someone will review your pull request soon

**Comment by karato** [comment]
@original-brownbear review it

**Comment by amihaiemil** [comment]
@original-brownbear  In the 3rd commit I fixed the failing app-veyor build, which failed because it could not find the ``${argLine}`` param. Long story short, this param has to be appended to the arguments of surefire in order for jacoco to run ok (see [here](http://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html)). 

However, the build fails if the jacoco profile is not run, since it cannot resolve the ``${argLine}`` for surefire (it is not previously set by jacoco). So 2 options to fix this - credits to @mkordas which had the same issue in another ticket: 

    1)  run jacoco always or
    2)  put <properties><argLine></argLine></properties> to POM

I tried the second, but it did not work. So we are left with running jacoco at each build. I also removed ``<pluginManagement>`` since it didn't work with it and anyway it didn't find it's purpose, since it is meant for inheriting plugins and no one inherits pom.xml from netbout.

**Comment by original-brownbear** [comment]
@amihaiemil will review it first thing tomorrow morning, until then, note that the coverage displayed here is 41% vs. 48%, so something seems to be up still right ?

**Comment by charlesmike** [comment]
@original-brownbear nope, i dont think so. I think 41 is the correct one. Im not sure what the 48 which is now in the freadme means... if you click on it, it takes you to coveralls but its only one built there, made by Yegor a ling time ago and there's all sorts of strange files listed there. I would trust this 41%

**Comment by amihaiemil** [comment]
@original-brownbear nope, i dont think so. I think 41 is the correct one. Im not sure what the 48 which is now in the freadme means... if you click on it, it takes you to coveralls but its only one built there, made by Yegor a ling time ago and there's all sorts of strange files listed there. I would trust this 41%

**Comment by original-brownbear** [comment]
@amihaiemil 

> I tried the second, but it did not work. So we are left with running jacoco at each build. I also removed <pluginManagement> since it didn't work with it and anyway it didn't find it's purpose, since it is meant for inheriting plugins and no one inherits pom.xml from netbout.

Well Netbout is made up of the parent pom and 3 submodules ? :) That being said, if it works to run Jacoco from the parent instead of the children individually, fine with me though :)

> I tried the second, but it did not work.

Why not ? What was the exact issue here? This should work for sure :) If it doesn't it should be easy to figure out why :)

**Comment by amihaiemil** [comment]
@original-brownbear I am not sure why it's not working with the second... I mean it's working if I don't run the jacoco profile, but then the jacoco profile doesn't run well with it. 

It somehow overrides what jacoco sets... see [this](http://stackoverflow.com/questions/18107375/getting-skipping-jacoco-execution-due-to-missing-execution-data-file-upon-exec) question - that's the problem; it happens when jacoco doesn't see that argLine. And if you google more you'll see a lot of people had the same issue and it's never clear, only that the argLine has to be appended to surefire. 

It's really a pain and I've been struggling with it for almost 3 days now. This here is my best solution and I have no idea how to make it better, sorry.

**Comment by amihaiemil** [comment]
@original-brownbear what do you think?

**Comment by original-brownbear** [comment]
@amihaiemil sorry for the delay, rough day :) Can't you just set some general arg line by default, as we do in other projects of ours like e.g.:

```xml
<plugin>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>2.12.1</version>
  <configuration>
    <argLine>-server -ea -XX:MaxPermSize=256m -Xmx4g -XX:-UseSplitVerifier ${argLine}</argLine>
  </configuration>
</plugin>
```
(really just an example, this is a version I know to work)

this should work just fine with and without Jacoco won't it ?

**Comment by amihaiemil** [comment]
@original-brownbear The current surefire config is the same as you say:
```
<configuration>
    <argLine>${argLine} -Dfile.encoding=UTF-8 -Djava.awt.headless=true</argLine>
</configuration>
```
and it fails if there is no jacoco run. Just now I also tried moving ``${argLine}`` at the end (as if by some twisted logic it would make a difference) but it's the same. Most likely in your case it works without jacoco because there's some other plugin or something else that sets ``${argLine}``

**Comment by amihaiemil** [comment]
@original-brownbear As I said, this issue was found also by @mkordas (with the same task) in one of the hadoop projects, and they resolved to this solution as well

**Comment by original-brownbear** [comment]
@amihaiemil ok, this is really the `ARC` job then :) thanks for the info :)

**Comment by original-brownbear** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@original-brownbear one more commit (I had forgotten to take out the jacoco profie from travis,yml)

**Comment by amihaiemil** [comment]
@dmzaytsev can u merge this pls?

**Comment by amihaiemil** [comment]
@dmzaytsev ping

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by karato** [comment]
@rultor deploy

**Comment by ypshenychka** [comment]
@original-brownbear 
According to our [QA Rules](http://at.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by original-brownbear** [comment]
@ypshenychka I confirm :)

**Comment by ypshenychka** [comment]
@original-brownbear Thanks.

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.
> 

@ypshenychka thanks a lot, next time everybody should try to make it better

**Comment by karato** [comment]
@original-brownbear I added 10 mins to @ypshenychka (for QA review) in transaction 101452096; **21 mins** was added to your account, many thanks for your contribution (payment AP-6VS48976L9507080M)! The task took 92 hours and 26 mins.; review comments (c=6) added as a bonus; +21 added to your rating, at the moment it is: [+8882](http://www.netbout.com/b/36646?open=rating)

**Pull request merged**
