### PR TITLE
#1015 fixes the definition of the Netbout local mode

### PR DESCRIPTION
**Pull request by dmzaytsev**
for #1015 
* fixes the definition of the Netbout local mode
* changed the test

### CODE REVIEW

**Comment by karato** [comment]
@dmzaytsev Many thanks, I will find someone to review it before we merge

**Comment by karato** [comment]
@dmzaytsev it's a very short pull request coming from the architect, there won't be any code review

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@mkordas do this review

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by mkordas** [comment]
@dmzaytsev what is going on here? Why this PR has invalid label?

**Comment by dmzaytsev** [comment]
@mkordas `invalid` label has been set by  @karato  to prevent both the code and QA review as it's a  very shot pull request. 
It seems some bug here as he assigned you as reviewer to this one at the same time.

@yegor256  please take a look

**Comment by dmzaytsev** [comment]
@rultor merge

**Pull request merged**
