### PR TITLE
 Autocompletion doesn't filter #995 

### PR DESCRIPTION
**Pull request by 2686747**
[#995](https://github.com/yegor256/netbout/issues/995) fix

### CODE REVIEW

**Comment by karato** [comment]
@2686747 Thanks, I will find someone to review this PR soon

**Comment by karato** [comment]
@dmzaytsev review this pull request please, it is rather short for a full review

**Comment by dmzaytsev** [comment]
@2686747 did you test your fix on the local instance?
please post a screenshot like the screenshot from the original ticket

**Comment by 2686747** [comment]
2016 02 12-13 27 56 928006207-max-vaio-arch
2016 02 12-13 28 10 158751160-max-vaio-arch
2016 02 12-13 28 19 022869219-max-vaio-arch
2016 02 12-13 28 25 704717394-max-vaio-arch

**Comment by dmzaytsev** [comment]
@2686747 thank you

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Thanks for your contribution, **18 mins** was added to your account, payment ID is `77265552`, 2 hours and 9 mins spent total. extra minutes for review comments (c=3). +18 added to your rating, current score is: [+3118](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
