### PR TITLE
Text form starts with a space

### PR DESCRIPTION
**Pull request by jhyle**
#978 remove trailing space in message field

### CODE REVIEW

**Comment by karato** [comment]
@jhyle Many thanks for the PR, let me find a reviewer for it

**Comment by karato** [comment]
@dmzaytsev pull request is rather short, review it please

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by krzyk** [comment]
@rultor deploy

**Comment by dmzaytsev** [comment]
@krzyk there is a bug in Rultor
I can't confirm the deploy

**Comment by krzyk** [comment]
@dmzaytsev I just noticed that it works on snapshot.netbout.com, it is deployed there after each merge?

**Comment by dmzaytsev** [comment]
@krzyk it is deployed after deploy only
it seems  deployed by @karato in another PR

**Comment by karato** [comment]
@dmzaytsev Thank you, I have added **18 mins** to your account in payment/transaction "`75932082`", time consumed: 13 hours and 56 mins

review comments (c=3) added as a bonus

+18 to your rating, your total score is [+2843](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
