### PR TITLE
#1080 hide stack trace for invalid email

### PR DESCRIPTION
**Pull request by TommyWind**
#1080

changed exception type, so stack trace not to be shown in browser.

### CODE REVIEW

**Comment by karato** [comment]
@tommywind Thanks, let me find someone who can review this pull request

**Comment by karato** [comment]
@dmzaytsev review it please, it is a rather short pull request, no need to do a full code review

**Comment by dmzaytsev** [comment]
@TommyWind `Alias.InvalidEmailException` extends `IOException` so it should be catched in `TkSaveEmail`. But it's not. It looks like a bug
I would suggest create a integration test that reproduces the issue an fix the bug

**Comment by dmzaytsev** [comment]
@TommyWind Actually we shouldn't change a class visibility just for a test 
so please revert your changes in `EmAlias`.
You can use mocked `Alias` for your test
mocked `Alias` that throws `Alias.InvalidEmailException` on changing email

**Comment by TommyWind** [comment]
@dmzaytsev updated PR.
I added now email validation functionality to MkAlias (otherwise test passes always). But in this case another Test (TkInviteTest) fails. The current logic seems to be right for me. So I would say there is something wrong with TkInviteTest. I haven't looked detailed at it yet because it might not be the scope of this ticket. What would you say? What should I do in this case?
Thank you in advance.

**Comment by dmzaytsev** [comment]
@TommyWind I  don't see any failed tests in the build log
just qulice complains
>[ERROR] \src\test\java\com\netbout\rest\account\TkSaveEmailTest.java[29]: Unused import - com.jcabi.email.Postman. (UnusedImportsCheck) 
[ERROR] \src\test\java\com\netbout\rest\account\TkSaveEmailTest.java[39]: Unused import - org.mockito.Mockito. (UnusedImportsCheck)

**Comment by TommyWind** [comment]
@dmzaytsev it fails on travis exactly as on my site, please take a look here https://travis-ci.org/yegor256/netbout/builds/118863771#L2006 .
PR is updated, removed unused imports.

**Comment by dmzaytsev** [comment]
@TommyWind you have added the email validation to MkAlias that's why the test failed.
> Email 'foo@bar.airforce' is wrong

Just change the email in TkInviteTest

**Comment by TommyWind** [comment]
@dmzaytsev pushed, looks like on Travis this is just a random issue with downloading PhantomJS

https://travis-ci.org/yegor256/netbout/builds/118971575#L188
´´´
Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
Error requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {
    "User-Agent": "npm/1.4.28 node/v0.10.36 linux x64"
  },
  "strictSSL": true
}
```

**Comment by dmzaytsev** [comment]
@TommyWind thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Thanks a lot, I just topped your account for **21 mins**, transaction ID `81881698`, total time was 358 hours and 12 mins; review comments (c=6) added as a bonus; +21 added to your rating, at the moment it is: [+3198](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
