### PR TITLE
#850 Multiple tests do not work on Windows due to encoding set to 'windows-1250' by default 

### PR DESCRIPTION
**Pull request by kujtimiihoxha**
For #850
 - Incorporated file encoding in the POM.

### CODE REVIEW

**Comment by karato** [comment]
@kujtimiihoxha Thanks for the pull request, let me find a reviewer..

**Comment by karato** [comment]
@dmzaytsev pull request is rather short, review it please

**Comment by dmzaytsev** [comment]
@kujtimiihoxha did you test the build  without default utf-8 encoding ?

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  The build is OK with and without the utf-8.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev done, I added **18 mins** in payment `78550607`, 23 hours and 1 min spent to complete this

extra minutes for review comments (c=3)

+18 added to your rating, at the moment it is: [+3462](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
