### PR TITLE
#646 return-after-login feature

### PR DESCRIPTION
**Pull request by komaz**
Fix for issue #646. Added explicit setting of cookie path in `RsReturn`, and decoding of cookie value in `TkReturn`

### CODE REVIEW

**Comment by karato** [comment]
@komaz Thanks, I will find someone to review this PR soon

**Comment by karato** [comment]
@caarlos0 review it

**Comment by caarlos0** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor merge please

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by karato** [comment]
@rultor deploy pls

**Comment by ypshenychka** [comment]
@caarlos0 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. Try to find at least three problems while future reviews.

Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by caarlos0** [comment]
@ypshenychka sure, I'll try

**Comment by ypshenychka** [comment]
@caarlos0 Thanks!

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the QA review, we'll work better next time

**Comment by karato** [comment]
@caarlos0 just added 10 mins to @ypshenychka (for QA), payment ID is `58229792`... done, I added **17 mins** in payment `AP-60C81072AX110794J`, 4 hours and 34 mins spent to complete this... extra minutes for review comments (c=2)... added +17 to your rating, now it is equal to [+2067](http://www.netbout.com/b/35095?open=rating)

**Pull request merged**
