### PR TITLE
Added link to message. (Issue #643)

### PR DESCRIPTION
**Pull request by antonini**
Added link to message. (Issue #643)

### CODE REVIEW

**Comment by karato** [comment]
@antonini Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by dmzaytsev** [comment]
@karato why you added the postponed tag?
please assign someone to do a code review

**Comment by karato** [comment]
@dmzaytsev pull request is rather short, review it please

**Comment by dmzaytsev** [comment]
@antonini what about a test?

**Comment by dmzaytsev** [comment]
@antonini I think your decision won't be work properly. It isn't enough just to add the message number to the href. Try to test it on your local instance. Netbout doesn't read all messages at once. It reads the messages when you scroll the list.

**Comment by antonini** [comment]
@dmzaytsev You are write. I need to change JS too. But I fond a problem over here. If i do same thing (#msgID) when the user access it and is an old message, the message doesn't appears on top of the browser. If I use ?start=ID&amp;_=OlderID the system doesn't load newer messages. So user would think there is nothing new on the bout.

**Comment by antonini** [comment]
@yegor256 I need your help over here. Can you check the comment above?

**Comment by yegor256** [comment]
@antonini I read the messages above but I don't see how I can help. What exactly is the question and why @dmzaytsev can't help (he is the architect in this project)?

**Comment by antonini** [comment]
@yegor256 Sorry, I thought you were the arch. The question is about how to expose old messages with a unique link that will place the message on top of browser (scroll down to the message) and at same time, loading all the recent content.

**Comment by yegor256** [comment]
@antonini no, I'm not the architect here. All such questions should be answered by @dmzaytsev, he is fully in charge of the project

**Comment by antonini** [comment]
@yegor256 Thanks. And sorry for that.

**Comment by dmzaytsev** [comment]
@antonini I think for the user it is supposed to look like the window is scrolling down so long as the message will appear on the top of the window. The user looks on the position of the scrollbar and he will understand that there are some messages  above.
I don't know how to implement it in the js. It's you task you should propose the decision and implement it. If I'm not mistaken you asked recently assign this task to you...

**Comment by antonini** [comment]
@dmzaytsev Source code is available.

**Comment by dmzaytsev** [comment]
@antonini thanks!
but I see no tests..
Take a look some tests in netbout-web/src/test/casperjs
I think you have to add a test for query a message link

**Comment by antonini** [comment]
@dmzaytsev Thanks for the help. Source code and tests available.

**Comment by dmzaytsev** [comment]
@antonini looks good, thanks
you right, a message should be highlighted when it accessed from a permalink,
please create a puzzle for this.

**Comment by antonini** [comment]
@dmzaytsev Puzzle added!

**Comment by dmzaytsev** [comment]
@antonini  rultor won't accept the puzzle description, please change it to `@todo #643:30min/DEV`

**Comment by antonini** [comment]
@dmzaytsev Changed.

**Comment by dmzaytsev** [comment]
@antonini thanks!

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by karato** [comment]
@rultor deploy

**Comment by karato** [comment]
@dmzaytsev Thanks for your contribution, **25 mins** was added to your account, payment ID is `60708112`, 229 hours and 25 mins spent total; you're getting extra minutes here (c=10); +25 added to your rating, current score is: [+2666](http://www.netbout.com/b/35166?open=rating)

**Pull request merged**
