### PR TITLE
#981 PDD check on Travis is not working for pom.xml 

### PR DESCRIPTION
**Pull request by kujtimiihoxha**
For #981
- Added .pdd file and configurations.

### CODE REVIEW

**Comment by kujtimiihoxha** [comment]
@dmzaytsev could you add a new issue to update the puzzles because the .pdd is working how it should.

**Comment by karato** [comment]
@kujtimiihoxha Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
@dmzaytsev the pull request is rather small, pls review it

**Comment by dmzaytsev** [comment]
@kujtimiihoxha you can update these puzzles in this PR
there are just three puzzles

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I updated the tickets.

**Comment by kujtimiihoxha** [comment]
@dmzaytsev could you merge now ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha yes we can
thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev **18 mins** sent to your balance (ID `77126918`), many thanks! It took 3 hours and 28 mins.

you're getting extra minutes here (c=3)

+18 to your rating, your total score is [+3078](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
