### PR TITLE
#604 MarkdownTest fails on Windows

### PR DESCRIPTION
**Pull request by komaz**
Added replacement of `\n` with platform-dependent line.separator. Tested locally by running with `mvn clean install -Pqulice -Dline.separator=$'\r\n'`

### CODE REVIEW

**Comment by karato** [comment]
@komaz Let me find a reviewer for this pull request, thanks for submitting it

**Comment by karato** [comment]
@caarlos0 do this review

**Comment by caarlos0** [comment]
@rultor good to merge

**Comment by dmzaytsev** [comment]
@rultor merge please

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by karato** [comment]
@rultor deploy now pls

**Comment by ypshenychka** [comment]
@caarlos0 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. We should get used to this rule as soon as possible.
Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by ypshenychka** [comment]
@karato Please assign @caarlos0 to this PR as far as he was code reviewer.

**Comment by caarlos0** [comment]
@ypshenychka sure, I'll try.

**Comment by ypshenychka** [comment]
@caarlos0 thanks! Let's try to make high-quality tickets :)

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thank you, let's try to make it "good" next time

**Comment by karato** [comment]
@caarlos0 just added 10 mins to @ypshenychka (for QA), payment ID is `58180838`... done, I added **17 mins** in payment `AP-7W875582XV187492P`, 19 hours and 18 mins spent to complete this... review comments (c=2) added as a bonus... +17 added to your rating, at the moment it is: [+2059](http://www.netbout.com/b/35095?open=rating)

**Pull request merged**
