### PR TITLE
947 fixed the email validation

### PR DESCRIPTION
**Pull request by dmzaytsev**
for #947 

* fixed regexp for the case when email was be empty before the changing
* added unit tests
* created a new puzzle to disable the email validation when Netbout running localy.
  it doesn't make sense to send a verification link when we haven't access to email server

### CODE REVIEW

**Comment by karato** [comment]
@dmzaytsev Many thanks, I will find someone to review it before we merge

**Comment by karato** [comment]
@krzyk do this review

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by karato** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by karato** [comment]
@rultor please deploy

**Comment by ypshenychka** [comment]
@krzyk 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by krzyk** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@krzyk Thanks.

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks a lot, next time everybody should try to make it better

**Comment by karato** [comment]
@krzyk just added 10 mins to @ypshenychka (for QA), payment ID is `75242842`; done, I added **17 mins** in payment `75242851`, 20 hours and 19 mins spent to complete this; extra minutes for review comments (c=2); +17 to your rating, your total score is [+4093](http://www.netbout.com/b/35035?open=rating)

**Pull request merged**
