### PR TITLE
#981  New issue PDD check on Travis is not working for pom.xml 

### PR DESCRIPTION
**Pull request by kujtimiihoxha**
For #981
 - Removed  duplicated source and verbose property

### CODE REVIEW

**Comment by karato** [comment]
@kujtimiihoxha Thanks, I will find someone to review this PR soon

**Comment by karato** [comment]
@dmzaytsev review it please, it is a rather short pull request, no need to do a full code review

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  please review this PR

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev I added **16 mins** to your account, many thanks for working with the project (77189204)! The completion time here was 3 hours and 6 mins.... review comments (c=1) added as a bonus... +16 added to your rating, current score is: [+3059](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy now pls

**Pull request merged**
