### PR TITLE
#820: Facebook login doesn't work

### PR DESCRIPTION
**Pull request by bdragan**
#820: (Facebook login doesn't work): Increased the restfb dependency version to 1.15.0.

### CODE REVIEW

**Comment by karato** [comment]
@bdragan Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
@dmzaytsev review it please, it is a rather short pull request, no need to do a full code review

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Thanks so much! Your account was topped up for **16 mins** (transaction ID is `68039231`, the task took 2 hours and 27 mins); review comments (c=1) added as a bonus; +16 added to your rating, at the moment it is: [+1448](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
