### PR TITLE
 #982 pom.xml:330-339: investigate error messages of the...

### PR DESCRIPTION
**Pull request by kujtimiihoxha**
For  #982.
      -Added repository property to resolve Error- No repository field
      -Added description
      -Added private to avoid Error- No readme

### CODE REVIEW

**Comment by karato** [comment]
@kujtimiihoxha Let me find a reviewer for this pull request, thanks for submitting it

**Comment by karato** [comment]
@krzyk do this review

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by karato** [comment]
@rultor deploy

**Comment by ypshenychka** [comment]
@krzyk 
According to our [QA Rules](http://at.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by ypshenychka** [comment]
@kujtimiihoxha 
According to our [QA Rules](http://at.teamed.io/qa.html):
>Pull request title explains the problem it is fixing.

Title ss copied from original puzzle and doesn't provide appropriate info. Please correct the title.

**Comment by krzyk** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@krzyk Thanks.

**Comment by kujtimiihoxha** [comment]
@ypshenychka Title changed.

**Comment by ypshenychka** [comment]
@kujtimiihoxha Thank you.

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by karato** [comment]
@krzyk just added 10 mins to @ypshenychka (for QA), payment ID is `76579304`. **17 mins** added to your account (payment number `76579323`), many thanks for your contribution! 18 hours and 9 mins spent here.. review comments (c=2) added as a bonus. +17 added to your rating, current score is: [+5209](http://www.netbout.com/b/35035?open=rating)

**Pull request merged**
