### PR TITLE
#748: Removed the puzzle from the code

### PR DESCRIPTION
**Pull request by bdragan**
#748: Removed the puzzle from the code.

### CODE REVIEW

**Comment by karato** [comment]
@bdragan Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
@dmzaytsev review it please, it is a rather short pull request, no need to do a full code review

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@karato please deploy

**Comment by karato** [comment]
> @karato please deploy

@dmzaytsev I don't deploy, @rultor does :)

**Comment by dmzaytsev** [comment]
@karato rultor doesn't listen to me now :)
only you can say deploy to him

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by karato** [comment]
@dmzaytsev Thank you, I have added **19 mins** to your account in payment/transaction "`68531694`", time consumed: 13 hours and 13 mins. you're getting extra minutes here (c=4). +19 to your rating, your total score is [+1442](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
