### PR TITLE
#904 Error handling on invalid 'since' value

### PR DESCRIPTION
**Pull request by exper0**
#904 Error handling on invalid 'since' value

### CODE REVIEW

**Comment by exper0** [comment]
@karato please assign reviewer

**Comment by karato** [comment]
@exper0 Many thanks for the PR, let me find a reviewer for it

**Comment by karato** [comment]
@pinaf review it

**Comment by karato** [comment]
> @karato please assign reviewer

@exper0 OK, got it

**Comment by pinaf** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@exper0 what about a test for a valid `since` value ?

**Comment by exper0** [comment]
@dmzaytsev done, see updated commit.

**Comment by dmzaytsev** [comment]
@exper0 thank you

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by karato** [comment]
@rultor deploy

**Comment by ypshenychka** [comment]
@pinaf 
According to our [QA Rules](http://at.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by pinaf** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@pinaf Thank you.

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by karato** [comment]
@pinaf added 10 mins to @ypshenychka, for QA review, payment code is `75342794`. I just added **17 mins** to your account, many thanks for your contribution (AP-0NF63723UT008723V).. 26 hours and 1 min spent here. extra minutes for review comments (c=2). +17 added to your rating, current score is: [+6228](http://www.netbout.com/b/35128?open=rating)

**Pull request merged**
