### PR TITLE
Fixed loading more messages when requesting a new page returns an HTML. (Issue #728)

### PR DESCRIPTION
**Pull request by antonini**
Fixed loading more messages when requesting a new page returns an HTML. (Issue #728)

### CODE REVIEW

**Comment by karato** [comment]
@antonini Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@dmzaytsev pull request is rather short, review it please

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by karato** [comment]
@dmzaytsev I added **17 mins** to your account, many thanks for working with the project! The completion time here was 61141860.. you're getting extra minutes here (c=2). +17 added to your rating, current score is: [+2622](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor please deploy

**Pull request merged**
