### PR TITLE
Fix for #963 - Delete temporary files created by the H2Sql class

### PR DESCRIPTION
**Pull request by danff**
Fix for #963 
- Marked the files created by the H2Sql class to be deleted on exit.

### CODE REVIEW

**Comment by karato** [comment]
@danff I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by karato** [comment]
@dmzaytsev review this pls (it's a rather short pull request)

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Many thanks! **16 mins** were added to your account in Transaction ID `77277686` (task took 1 hour and 47 mins); extra minutes for review comments (c=1); +16 added to your rating, current score is: [+3134](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor please deploy

**Pull request merged**
