### PR TITLE
 #992 Deployment failed due to the coverage report not exists

### PR DESCRIPTION
**Pull request by kujtimiihoxha**
For  #992 
 - Removed clean from the last command to use Coberura report from the previous step.

### CODE REVIEW

**Comment by karato** [comment]
@kujtimiihoxha Thanks for the pull request, let me find a reviewer..

**Comment by karato** [comment]
@dmzaytsev pull request is rather short, review it please

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev I just added **16 mins** to your account, many thanks for your contribution (77941846).. 16 hours and 18 mins spent here; review comments (c=1) added as a bonus; added +16 to your rating, now it is equal to [+3301](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy now pls

**Pull request merged**
