### PR TITLE
#941 Local Netbout doesn't allow to start a new bout

### PR DESCRIPTION
**Pull request by kujtimiihoxha**
For #941
    -Removed email checking for first page.

### CODE REVIEW

**Comment by karato** [comment]
@kujtimiihoxha Thanks, let me find someone who can review this pull request

**Comment by karato** [comment]
@mkordas do this review

**Comment by mkordas** [comment]
@kujtimiihoxha I see that you've made changes not only to local instance, but also to the production. Can you explain?

**Comment by kujtimiihoxha** [comment]
@ mkordas I do not understand what you mean, please explane.

**Comment by mkordas** [comment]
@kujtimiihoxha Issue is about disabling email check when Netbout runs locally. But you've modified `netbout-web/src/main/xsl/layout.xsl` which will change application behaviour not only locally.

**Comment by mkordas** [comment]
@kujtimiihoxha please also edit comment and remove space between `@` and `mkordas`

**Comment by kujtimiihoxha** [comment]
@mkordas  Ok I did not understand the task right, Can I close this pull request and submit another when I complete the task ?

**Comment by mkordas** [comment]
@kujtimiihoxha Ideally we should have just one pull request for one issue. You can always push new commits to this branch with `push --force`.

**Comment by kujtimiihoxha** [comment]
@mkordas Ok I will push here. thanks.

**Comment by mkordas** [comment]
@kujtimiihoxha all right, I'm waiting. Notify me with `@mkordas`

**Comment by mkordas** [comment]
@kujtimiihoxha I'm working only for 2 more hours today, otherwise I'll review things tomorrow

**Comment by kujtimiihoxha** [comment]
@mkordas its ok , tonight I can't make it.

**Comment by mkordas** [comment]
@kujtimiihoxha do you need any help?

**Comment by kujtimiihoxha** [comment]
@mkordas  yes , I do not fully understand the project structure so I could not find a solution to only affect the local instance , If you could give me some clues on where I could do this that would be helpful.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha btw you not assigned to #942

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I was assigned to this task I don't know why I am not now ?

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  Sorry task is for #941

**Comment by dmzaytsev** [comment]
@kujtimiihoxha you have asked how to know when Netbout runs locally, right?
I would propose to use `Manifests.read("Netbout-Version").contains("LOCAL")`

**Comment by kujtimiihoxha** [comment]
@mkordas  I think everything should be OK now, sorry for the delay. @dmzaytsev thank you very much for the help, I used something very similar in xsl.

**Comment by mkordas** [comment]
@kujtimiihoxha can you provide screenshots proving that fix really works?

**Comment by kujtimiihoxha** [comment]
@mkordas here is the screen shot.
startlink

**Comment by kujtimiihoxha** [comment]
@mkordas  could you please merge now ? Or do you need anything else.

**Comment by mkordas** [comment]
@kujtimiihoxha looks good now

**Comment by mkordas** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by mkordas** [comment]
@rultor deploy

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by karato** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by karato** [comment]
@rultor deploy pls

**Comment by ypshenychka** [comment]
@mkordas 
ccording to our [QA Rules](http://at.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

Only one issue was found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by mkordas** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@mkordas Thank you

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the QA review, we'll work better next time

**Comment by karato** [comment]
@mkordas just added 10 mins to @ypshenychka (for QA), payment ID is `75308997`; I added **28 mins** to your account, many thanks for working with the project (56a4e5c6d0ff9b018e000344)! The completion time here was 71 hours and 40 mins.; you're getting extra minutes here (c=13); +28 added to your rating, current score is: [+3348](http://www.netbout.com/b/36080?open=rating)

**Pull request merged**
