### PR TITLE
#847 Markdown interface introduced

### PR DESCRIPTION
**Pull request by dmzaytsev**
For #847 

* introduced Markdown interface to convert Markdown-formatted text to its html representation
* Previous `Markdown` with PegDown implementation renamed to  MarkdownPegDown
* Created a new puzzle to implement MarkdownTxtmark

### CODE REVIEW

**Comment by karato** [comment]
@dmzaytsev Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@caarlos0 do this review

**Comment by caarlos0** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by karato** [comment]
@rultor please deploy

**Comment by ypshenychka** [comment]
@caarlos0 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by caarlos0** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thank you, let's try to make it "good" next time

**Comment by karato** [comment]
@caarlos0 added 10 mins to @ypshenychka, for QA review, payment code is `71917815`

Thanks so much! Your account was topped up for **17 mins** (transaction ID is `566d9ed2d4a82e60df000098`, the task took 5 hours and 26 mins)

you're getting extra minutes here (c=2)

added +17 to your rating, now it is equal to [+376](http://www.netbout.com/b/35095?open=rating)

**Pull request merged**
