### PR TITLE
#1045 shifted back to PegDown

### PR DESCRIPTION
**Pull request by dmzaytsev**
for #1045

### CODE REVIEW

**Comment by dmzaytsev** [comment]
@yegor256 Could you review this PR?
or can we skip the review?

**Comment by dmzaytsev** [comment]
@karato this is invalid

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Thanks, let me find someone who can review this pull request

**Comment by karato** [comment]
> @karato this is invalid

@dmzaytsev sure, thanks, I added "invalid" label to it

**Pull request merged**
