### PR TITLE
#715 fixed return after login looses query params

### PR DESCRIPTION
**Pull request by dmzaytsev**
For #715 
* fixed bug "return after login looses query params"

### CODE REVIEW

**Comment by karato** [comment]
@dmzaytsev Thanks for the pull request, let me find a reviewer..

**Comment by karato** [comment]
@dmzaytsev no need to do code review here, it's a small pull request from the architect

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor deploy

**Pull request merged**
