### PR TITLE
#858 XSS vulnerability in bouts 

### PR DESCRIPTION
**Pull request by kujtimiihoxha**
For #858
 - Enabled safe mode
Now it looks like this :  
capture

### CODE REVIEW

**Comment by karato** [comment]
@kujtimiihoxha Thanks, I will find someone to review this PR soon

**Comment by karato** [comment]
@dmzaytsev pull request is rather short, review it please

**Comment by dmzaytsev** [comment]
@kujtimiihoxha what about a test ?

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I am using this 
```
  MatcherAssert.assertThat(
            new MarkdownTxtmark().html(
                "<script>alert()</script>"
            ),
            Matchers.equalTo(
                "<p>&lt;script>alert()&lt;/script></p>\\n"
            )
        );
```
but I am getting 
```
Expected: "<p>&lt;script>alert()&lt;/script></p>\n"
     but: was "<p>&lt;script>alert()&lt;/script></p>\n"
```
But the two lines are identical ?

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I solved it very interesting it does note like the ```\n``` at the end now it works.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha AppVeyor build failed
let's fix it

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Can I suppress ToManyMethods PMD violation?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha yes, you can in a test class

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  I think everything is OK now.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Thank you, I have added **20 mins** to your account in payment/transaction "`78675389`", time consumed: 4 hours and 16 mins. extra minutes for review comments (c=5). added +20 to your rating, now it is equal to [+3649](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
