### PR TITLE
#606 Add @mention autocompletion

### LINKED ISSUE #606: @mention autocompletion
I believe netbout needs `@mention` autocompletion like Github.
When you type an @ and you should see a list of people on the boat. Continue typing to filter the list and hit enter or tab to complete the name. 

updated 6/10/2015:
you might to use e.g. this autocompletion implementation https://github.com/podio/jquery-mentions-input but feel free to propose another. I spent 3 mins to google it....

### PR DESCRIPTION
**Pull request by mbarbieri**
Added mention autocompletion Github style using [jQuery Textcomplete](https://github.com/yuku-t/jquery-textcomplete) plugin.

Fixes #606

### CODE REVIEW

**Comment by karato** [comment]
@mbarbieri Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
@caarlos0 review it

**Comment by caarlos0** [comment]
@mbarbieri seems like your jshint ignore didn't work...

**Comment by mbarbieri** [comment]
@caarlos0 yes I was about to write it... I tried several times but the only way to make it work was to ignore every file... Any suggestions?

**Comment by caarlos0** [comment]
@mbarbieri as I see we don't yet have a jslint config file, maybe it's related... might also be related to https://github.com/yegor256/netbout/issues/701

**Comment by caarlos0** [comment]
maybe the architect ( @dmzaytsev ) can help us out...

**Comment by dmzaytsev** [comment]
@caarlos0 unfortunatelly I'm not a Qulice expert.
@yegor256 could you help us here?
We need to disable the qulice check for the particular js-file

**Comment by yegor256** [comment]
@mbarbieri @dmzaytsev why do we need to disable jslint? let's just fix all errors. placing third-party JS file into our repository is a bad idea. It's not our code, we should NOT have in our repo.

**Comment by caarlos0** [comment]
@yegor256 good point. Question: how are we managing external JS deps in netbout?

**Comment by yegor256** [comment]
@caarlos0 I think we need to find a place where this `.js` file is hosted already and just point our HTML there. the worst case would be to use Github raw content

**Comment by caarlos0** [comment]
@yegor256 hmm no bower or grunt or whatever then?

**Comment by yegor256** [comment]
@caarlos0 maybe that too, why not. we can use bower to download this `.js` file during `mvn package` phase and place it into `target/classes/js`

**Comment by yegor256** [comment]
@caarlos0 google for `maven bower`, there are some interesting articles

**Comment by caarlos0** [comment]
@yegor256 yes, I used a maven grunt whatever plugin once for this, works perfectly... the tradeoff is that we will add node.js as a dependency...

**Comment by yegor256** [comment]
@caarlos0 it's OK, I don't see anything bad in node.js

**Comment by caarlos0** [comment]
@yegor256 yeah, me neither...

**Comment by mbarbieri** [comment]
@yegor256 including Github raw page is giving me problems:
```
Refused to execute script from 'https://raw.githubusercontent.com/yuku-t/jquery-textcomplete/master/dist/jquery.textcomplete.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```
Is there a way to exclude this file from qulice for now, or what else can be done?

**Comment by yegor256** [comment]
@mbarbieri another approach, as @caarlos0 suggested above, is to use bower or grunt

**Comment by caarlos0** [comment]
you can create a `.bowerrc` and a `package.json` and add something like this to the pom:

```xml
			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<version>0.0.20</version>
				<executions>
					<execution>
						<id>install node and npm</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<nodeVersion>v0.12.4</nodeVersion>
							<npmVersion>2.11.3</npmVersion>
						</configuration>
					</execution>
					<execution>
						<id>npm install</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>install</arguments>
						</configuration>
					</execution>
					<execution>
						<id>bower install</id>
						<goals>
							<goal>bower</goal>
						</goals>
						<configuration>
							<arguments>install</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

**Comment by caarlos0** [comment]
@mbarbieri ping

**Comment by mbarbieri** [comment]
@caarlos0 working on it

**Comment by mbarbieri** [comment]
@caarlos0 @yegor256 I think it's too much to configure Bower inside this task, so I added it as a puzzle, hoping that this is ok.

**Comment by dmzaytsev** [comment]
@yegor256 can we use boost factor here ?

**Comment by dmzaytsev** [comment]
@mbarbieri why we can't use [this link](http://yuku-t.com/jquery-textcomplete/media/javascripts/jquery.textcomplete.js) instead raw.githubusercontent.com ?
I got it from the author's page http://yuku-t.com/jquery-textcomplete/

**Comment by mbarbieri** [comment]
@dmzaytsev we will be dependent on the author's website availability and version.. Anyway it's still better than what I did previously... so now it's linked to the author's page.

**Comment by dmzaytsev** [comment]
@mbarbieri I mean to use this link as temporary decision, until the puzzle will resolved

**Comment by dmzaytsev** [comment]
@mbarbieri did you test it on the local instance?

**Comment by mbarbieri** [comment]
@dmzaytsev yes yes, it's working fine

**Comment by dmzaytsev** [comment]
@mbarbieri thanks!

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by karato** [comment]
@rultor deploy now pls

**Comment by ypshenychka** [comment]
@caarlos0 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.

Only one issue was found during code review. 
Please confirm that you will try to find at least three problems next time.

**Comment by ypshenychka** [comment]
@caarlos0 
>maybe the architect ( @dmzaytsev ) can help us out...

According to our [QA Rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct your message by indicating a person you're referring to in the beginning of it.

**Comment by caarlos0** [comment]
@ypshenychka fixed

**Comment by caarlos0** [comment]
@ypshenychka Yes, I'll try

**Comment by ypshenychka** [comment]
@caarlos0 Thanks a lot!

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks, got it. everybody, please try to make it good next time

**Comment by karato** [comment]
@caarlos0 I added 10 mins to @ypshenychka (for QA review) in transaction 60001149

done, I added **26 mins** in payment `AP-5UA908643T008752P`, 143 hours and 3 mins spent to complete this

extra minutes for review comments (c=11)

+26 added to your rating, at the moment it is: [+2532](http://www.netbout.com/b/35095?open=rating)

**Pull request merged**
