### PR TITLE
#878 add meta description tag

### PR DESCRIPTION
**Pull request by kitsook**
For issue #878 
- added meta `description` tag
- no need to add `title` as it is already in-place

### CODE REVIEW

**Comment by karato** [comment]
@kitsook Let me find a reviewer for this pull request, thanks for submitting it

**Comment by karato** [comment]
@dmzaytsev pull request is rather short, review it please

**Comment by dmzaytsev** [comment]
@kitsook let's add a CasperJs test to be ensure your changes affected to to the site

**Comment by dmzaytsev** [comment]
@kitsook but no, it would better to create an integration test instead of CasperJS
we need emulate a web crauler, not a client's browser

**Comment by kitsook** [comment]
@dmzaytsev revised. please review.
- description put inside the manifests file. let me know if you have other suggestions
- `XePage` modified to include the `documentation` tag in xml
- xslt will extract the `documentation` tag into html `meta` tag
- test cases added to `TkAppITCase`
- test cases use xpath to verify the xml/html output so jcabi-xml dependency added to pom.xml of netbout-web

**Comment by dmzaytsev** [comment]
@kitsook thank you

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Much appreciated! **19 mins** was added to your account, payment ID `75792866`, time spent is 49 hours and 48 mins; you're getting extra minutes here (c=4); +19 added to your rating, current score is: [+2816](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy now pls

**Pull request merged**
