### PR TITLE
#997 ignored space after inline link

### PR DESCRIPTION
**Pull request by dmzaytsev**
for #997 

* fixed the html links detection regexp to ignore spaces after a inline link
* added unit tests

### CODE REVIEW

**Comment by karato** [comment]
@dmzaytsev Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
@dmzaytsev it's a very short pull request coming from the architect, there won't be any code review

**Comment by karato** [comment]
@hdouss review it

**Comment by dmzaytsev** [comment]
@karato please remove `invalid` label from this PR or unassign @hdouss

**Comment by karato** [comment]
> @karato please remove `invalid` label from this PR or unassign @hdouss
> 

@dmzaytsev yes, @hdouss is already assigned to this task, please go ahead!

**Comment by HDouss** [comment]
>@dmzaytsev yes, @hdouss is already assigned to this task, please go ahead!
@karato You removed assignment, and there is always this invalid tag. Am I still assigned ?

**Comment by dmzaytsev** [comment]
@HDouss I guess it's a bug in an automation script
you not assigned now

**Comment by dmzaytsev** [comment]
@rultor merge

**Pull request merged**
