### PR TITLE
#812 Update jcabi-aspects to the latest version

### PR DESCRIPTION
**Pull request by mkordas**
For #812:
*  updated jcabi-aspects to 0.22.3
* rest of updates were needed to make build passing for various reasons (mainly lack of compatibility)

### CODE REVIEW

**Comment by karato** [comment]
@mkordas Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@dmzaytsev the pull request is rather small, pls review it

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev paid, thanks, added **16 mins** to your account, payment `74717591`, 1 hour and 4 mins was spent. you're getting extra minutes here (c=1). added +16 to your rating, now it is equal to [+1955](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
