### PR TITLE
#767 Fix MarkdownTest for Windows environment

### LINKED ISSUE #767: MarkdownTest broken on windows
We have a broken test on Windows
```
Failed tests:
  MarkdownTest.breaksSingleLine:170
Expected: "<p>line1\n<br />\nline2</p>\n<p>line3</p>"
     but: was "<p>line1\r\n<br />\r\nline2</p>\r\n<p>line3</p>"
```
let's fix it

### PR DESCRIPTION
**Pull request by mkordas**
Fixes #767.

### CODE REVIEW

**Comment by karato** [comment]
@mkordas Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
@dmzaytsev the pull request is rather small, pls review it

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Much obliged! I have added **16 mins** to your account in payment "72267098", 1 hour and 39 mins spent

you're getting extra minutes here (c=1)

+16 added to your rating, at the moment it is: [+962](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy now pls

**Pull request merged**
