### PR TITLE
 #1045 upgraded aws libs

### PR DESCRIPTION
**Pull request by dmzaytsev**
for #1045 
upgraded AWS dependencies to the latest version

### CODE REVIEW

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@karato this is invalid

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by original-brownbear** [comment]
@dmzaytsev not yet :)

**Comment by dmzaytsev** [comment]
@original-brownbear i hurried :)

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by dmzaytsev** [comment]
@rultor deploy

**Pull request merged**
