### PR TITLE
#616: change throwed exception class

### PR DESCRIPTION
**Pull request by lautarobock**
#616 just changed the throwen exception class that was wrong

### CODE REVIEW

**Comment by karato** [comment]
@lautarobock Thanks for the pull request, let me find a reviewer..

**Comment by dmzaytsev** [comment]
@karato this task is not postponed any more

**Comment by karato** [comment]
> @karato this task is not postponed any more

@dmzaytsev OK, I un-labeled it as "postponed" tag

**Comment by karato** [comment]
@caarlos0 do this review

**Comment by caarlos0** [comment]
@rultor merge

**Comment by dmzaytsev** [comment]
@rultor merge please

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by karato** [comment]
@rultor deploy

**Comment by ypshenychka** [comment]
@caarlos0 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

There were no issues found during review. We should get used to this rule as soon as possible.
Please confirm that you will try to find at least three problems next time.

**Comment by caarlos0** [comment]
@ypshenychka Ok, I'll try

**Comment by ypshenychka** [comment]
@caarlos0 Thanks

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by karato** [comment]
@caarlos0 just added 10 mins to @ypshenychka (for QA), payment ID is `58619874`... **17 mins** added to your account (payment number `AP-8YY42602WD2791136`), many thanks for your contribution! 4 hours and 12 mins spent here.... extra minutes for review comments (c=2)... +17 added to your rating, current score is: [+2013](http://www.netbout.com/b/35095?open=rating)

**Pull request merged**
