### PR TITLE
#791 Introduced parallel tests timeout

### PR DESCRIPTION
**Pull request by prahladyeri**
As a fix for #791 , I've added the `parallelTestsTimeoutInSeconds` parameter to the `pom.xml` in `netbout-client`. As a result, any network issues causing long delays in the test cases will not affect the build process.

**EDIT**
Made a permanent fix to freeze issue by removing the `ReUser` wrapper class. However, I still think that parallel tests timeout is needed as an overall check in `pom.xml` (though I've removed it for the time being).

### CODE REVIEW

**Comment by prahladyeri** [comment]
@dmzaytsev Why is this failing? All I did is add an attribute to `pom.xml` ?

**Comment by karato** [comment]
@prahladyeri Let me find a reviewer for this pull request, thanks for submitting it

**Comment by karato** [comment]
@dmzaytsev review this pls (it's a rather short pull request)

**Comment by dmzaytsev** [comment]
@prahladyeri I don't like your idea about the timeout
if you have looked RtFriendsITCase#invitesAndKicksOff() 
you can see  on first line  `final User user = this.rule.get();`
just one click and we see the reason of the stuck
https://github.com/yegor256/netbout/blob/master/netbout-client/src/test/java/com/netbout/client/NbRule.java#L56
I think we shouldn't use  `ReUser` here 
it repeat a method call if any problem occurs inside
just remove `ReUser` from this line

But in this case we have untested class ReUser
let's create a unit test for it

**Comment by dmzaytsev** [comment]
@prahladyeri 

> Why is this failing? All I did is add an attribute to pom.xml ?

don't hesitate to click on details...

we don't have a config file for AppVeyor yet that's why this check broken

**Comment by prahladyeri** [comment]
@dmzaytsev I removed the `ReUser` wrapper, then it went through the `RtAttachmentITCase` smoothly, but when it goes down in the `RtAliasITCase` it fails in the `updateAndRetrieveEmail`:

    updateAndRetrieveEmail(com.netbout.client.RtAliasITCase)  Time elapsed: 8.624 sec  <<< ERROR!
    com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/page/alias/email/text()' not found in '<?xml 
    version="1.0" encoding="UTF-8" standalone="n..7809..date>2011-09-23</date>\n</version>\n</page>\n': 
    Index (0) is out of bounds (size=0)

Am I supposed to add an email to the registered user `alex` or something like that?

**Comment by dmzaytsev** [comment]
@prahladyeri one issue -  one PR
is RtAliasITCase without user `alex`  stucked after you removed `ReUser` wrapper? 
do you resolve the issue that the original ticket reported?
if so just push your changes

**Comment by prahladyeri** [comment]
@dmzaytsev Done. Please see my new commit in the pull request.

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by prahladyeri** [comment]
@dmzaytsev I want to understand netbout in detail by going through the docs. Please confirm if this one I've found by Google search is the canonical:

http://maven.netbout.com/project-info.html

**Comment by karato** [comment]
@dmzaytsev Thanks for your contribution, **19 mins** was added to your account, payment ID is `73016558`, 23 hours and 42 mins spent total

extra minutes for review comments (c=4)

+19 added to your rating, current score is: [+1204](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor please deploy

**Pull request merged**
