### PR TITLE
 #859 Visual glitches when using markdown titles in bouts

### PR DESCRIPTION
**Pull request by kujtimiihoxha**
For  #859
 - Changed scss style.

### CODE REVIEW

**Comment by karato** [comment]
@kujtimiihoxha Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@dmzaytsev pull request is rather short, review it please

**Comment by dmzaytsev** [comment]
@kujtimiihoxha please submit a screenshot

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  here is a screenshot. 
screen

**Comment by dmzaytsev** [comment]
@kujtimiihoxha thanks

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by karato** [comment]
@dmzaytsev Much appreciated! **18 mins** was added to your account, payment ID `78550628`, time spent is 23 hours and 1 min

review comments (c=3) added as a bonus

+18 added to your rating, at the moment it is: [+3480](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
