### PR TITLE
#637 pretty formatted RsPage response

### PR DESCRIPTION
**Pull request by dmzaytsev**
For #637 

* pretty format output XML

### CODE REVIEW

**Comment by karato** [comment]
@dmzaytsev Thanks for the pull request, let me find a reviewer..

**Comment by karato** [comment]
@dmzaytsev it's a very short pull request coming from the architect, there won't be any code review

**Comment by dmzaytsev** [comment]
@karato this is not postponed anymore

**Comment by dmzaytsev** [comment]
@karato assign me to this please

**Comment by dmzaytsev** [comment]
@rultor merge

**Pull request merged**
